### ISSUE TITLE
Launcher won't start up

### ISSUE THREAD

**Issue by Xrot** [lucas-allegri/KnightLauncher#14]
Knight Launcher won't start up on my computer my OS is Win 7 Ult SP1 64-bit

**Comment by lucas-allegri** [comment]
Hello there, please try to start the launcher using either the windows .bat file or the debug .bat file, altogether if there's any logs in KnightLauncher/logs it'd be great to have them too.

Regards!

**Comment by Xrot** [comment]
i've deleted knightlauncher.properties and that fixed it

**Comment by lucas-allegri** [comment]
Nice to hear, this issue should be fixed upon release of Knight Launcher 1.3.2
