### ISSUE TITLE
Can't Open Game In Launcher.

### ISSUE THREAD

**Issue by NoobMaster-15** [lucas-allegri/KnightLauncher#19]
So, I can't open the game in the launcher, it just kept saying, " Can't find players count." What is that supposed to mean?

**Comment by lucas-allegri** [comment]
Please attach your log files so I can review this further.

**Comment by lucas-allegri** [comment]
I'll assume this is either solved or abandoned as there has been no response from the author since a week ago. Feel free to reopen this if persists.
