### ISSUE TITLE
KnightLauncher on MacOS

### ISSUE THREAD

**Issue by FlurryHearts** [lucas-allegri/KnightLauncher#2]
I’m having some trouble with starting SK with mods through the Launcher. Now every time I launch Spiral Knights, it says I have no Java on my computer. 

I believe the files become unreadable because I once deleted all my sk files and it gave the same message. 

The logs tell me that the mods have been mounted successfully and I haven’t downloaded any mods that arent compatible with the launcher.

Some extra info: without any mods, the game launches successfully through the Launcher.

**Comment by lucas-allegri** [comment]
Solved after the following commit:
https://github.com/lucas-allegri/KnightLauncher/commit/18ade7fe4ce04eea00bc3159e19cf7c1db7cd3d8

Thanks for reporting!
