### ISSUE TITLE
Post installation, SK now instantly closes upon opening from either Steam or Knight Launcher.

### ISSUE THREAD

**Issue by Cloudydaes** [lucas-allegri/KnightLauncher#22]
After installing Knight Launcher on a fresh installation of Spiral Knights, we've had the issue of the title now immediately closing as soon as it's opened, be it on the Knight Launcher, or Steam respectively. 

We're using KL Version 1,5, default settings with the exception of increased RAM allocation up to 8gb. 

Attached here are the most recent logs.
[launcher.log](https://github.com/lucas-allegri/KnightLauncher/files/5883859/launcher.log)

**Comment by lucas-allegri** [comment]
Please try renaming the directory `java_vm_unpatched` back to `java_vm`. Delete your current `java_vm` directory or rename it if you need to.

**Comment by Cloudydaes** [comment]
Unfortunately, said solution seems to be ineffective. Deleting the current java_vm forces a "Cannot create the virtual machine" error,  and renaming it results in the previous issue with the title immediately closing.

**Comment by lucas-allegri** [comment]
Try manually patching in the 64 bit Java VM using the latest Java version from java.com
(More info: https://steamcommunity.com/sharedfiles/filedetails/?id=1847575647)

**Comment by lucas-allegri** [comment]
Closing this issue as there has been no response for weeks. Feel free to re-open if it persists.
