### ISSUE TITLE
Cannot patch game to 64 bit: The Java VM download couldn't be initialized

### ISSUE THREAD

**Issue by nichitacebotari0** [lucas-allegri/KnightLauncher#24]
Setup: Steam game,have the .jar and windows batch file in the root folder.
One thing of note: On initial run of the lkauncher it said that it failed some update and wont try it the next time.Perhaps my "64 bit patch" failed and now I don thave a way to install it again?

Allocating 1.5 GB causes the game to start for a second(with sound) then crash.
Allocating 2 GB or more causes the game to fail with a message box that states: "Could not create the java virtual machine".

**Comment by nichitacebotari0** [comment]
Update: Found the button to retry the 64 bit patch,I will change the title now as I assume this to be the cause,but Ill leave the initial message as is for posterity.

Cannot patch game to 64 bit
![image](https://user-images.githubusercontent.com/37653982/118382973-a9ce6e00-b602-11eb-8c66-3179daacb24d.png)

**Comment by Milliath** [comment]
if it fails to download the 64-bit java you're probably stuck with 32-bit one that can't eat more than 1 GB RAM. try setting the default 512mb

**Comment by nichitacebotari0** [comment]
Yeah it does work with 1GB and lower(forgot to mention that sorry). Just thought I had to mention that the 64 bit downloading part doesn't work.

**Comment by lucas-allegri** [comment]
Fixed in version 1.5.3.
