### ISSUE TITLE
Steam account workaround for Linux

### ISSUE THREAD

**Issue by Thyrux** [lucas-allegri/KnightLauncher#3]
You might have already heard that there's no official Steam support on Linux. However it's still possible to play with Steam-bound account on Linux, but it requires certain workaround that I've described [here](https://wiki.spiralknights.com/Steam_FAQ#Playing_with_Steam_account_natively_on_Linux).

Would you add a "Steam workaround for Linux" setting that would make use of Shell script that acts as a launcher (original name "Spiral", but file should be manually selectable in file input field) instead of signaling Steam and running "official" Spiral Knights in Proton/WINE?

**Comment by lucas-allegri** [comment]
Totally, had to deal with it a couple of weeks ago and I can assure it's not an easy task to get running, gonna look into an implementation for a future release. Please keep this issue open.

**Comment by lucas-allegri** [comment]
After looking into it in detail, there's not an easy way to implement this since it'd always break the true standalone instance. In this situation I find best to users to patch it themselves then use the standalone platform inside Knight Launcher, instead of Steam.

Regards.
