### ISSUE TITLE
You need to place this .jar inside your Spiral Knights main directory

### ISSUE THREAD

**Issue by Tmerus** [lucas-allegri/KnightLauncher#8]
doesn't work if game in non program files folder :\ (launcher says that it doesn't game folder). Game installed on non system disk

![Скриншот 05-06-2020 010737](https://user-images.githubusercontent.com/66437631/83795076-20f84400-a6c9-11ea-985a-674be961ab2c.png)
![Скриншот 05-06-2020 010751](https://user-images.githubusercontent.com/66437631/83795078-22297100-a6c9-11ea-8c83-05be848e6b30.png)

**Comment by lucas-allegri** [comment]
Does your installation directory have a file named "getdown.pro.jar"?

**Comment by Tmerus** [comment]
> Does your installation directory have a file named "getdown.pro.jar"?

here but it getdown-pro.jar not getdown.pro.jar

![Скриншот 05-06-2020 023941](https://user-images.githubusercontent.com/66437631/83802951-e0eb8e00-a6d5-11ea-9398-1cb2b0cc3af7.png)

**Comment by lucas-allegri** [comment]
Please try again using the latest update.

**Comment by Tmerus** [comment]
> Please try again using the latest update.

same

![Скриншот 05-06-2020 032107](https://user-images.githubusercontent.com/66437631/83806414-adabfd80-a6db-11ea-8b59-f894ecde585a.png)

**Comment by Tmerus** [comment]
It start work when I change bat file to this - 

![image](https://user-images.githubusercontent.com/66437631/83867326-70835200-a753-11ea-8212-d3a4c397b5d0.png)

**Comment by lucas-allegri** [comment]
Glad to know it's working now 👍
